{
  "artifacts": [],
  "command": "my_main",
  "experiment": {
    "base_dir": "/naf_ikostrikov/src",
    "dependencies": [
      "gym==0.10.9",
      "munch==2.3.2",
      "numpy==1.15.4",
      "pymongo==3.7.2",
      "PyYAML==3.13",
      "sacred==0.7.4",
      "tensorboardX==1.6",
      "torch-nightly==1.0.0.dev20190115",
      "tqdm==4.29.1"
    ],
    "mainfile": "main.py",
    "name": "pymarl",
    "repositories": [],
    "sources": [
      [
        "ddpg.py",
        "_sources/ddpg_f92b208f47da5123923acffb1195055e.py"
      ],
      [
        "main.py",
        "_sources/main_4081869334b2a332f0defe1d232c88e0.py"
      ],
      [
        "naf.py",
        "_sources/naf_5b4f9a072eb4615b78703aa6f5e2eb17.py"
      ],
      [
        "normalized_actions.py",
        "_sources/normalized_actions_66c34f3bdd062b4c4a73adbb6fed467d.py"
      ],
      [
        "ounoise.py",
        "_sources/ounoise_e98eb3950934bca88d9c35aba79a06fb.py"
      ],
      [
        "param_noise.py",
        "_sources/param_noise_eb27360ba4ef6667ec21640232e18634.py"
      ],
      [
        "replay_memory.py",
        "_sources/replay_memory_0a39d2f1243e9f04206242d41aa091b5.py"
      ],
      [
        "utils/__init__.py",
        "_sources/__init___d41d8cd98f00b204e9800998ecf8427e.py"
      ],
      [
        "utils/dict2namedtuple.py",
        "_sources/dict2namedtuple_0afb1ea09dbaa5798eb9185aeaa09a13.py"
      ],
      [
        "utils/logging.py",
        "_sources/logging_35a5d480ff8d4889ba1e8320767e94ab.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/usr/local/lib/python3.5/dist-packages/gym/envs/mujoco/mujoco_env.py\", line 11, in <module>\n    import mujoco_py\n",
    "ImportError: No module named 'mujoco_py'\n",
    "\nDuring handling of the above exception, another exception occurred:\n\n",
    "Traceback (most recent call last):\n",
    "  File \"/usr/local/lib/python3.5/dist-packages/sacred/config/captured_function.py\", line 46, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"src/main.py\", line 255, in my_main\n    train(arglist, logger)\n",
    "  File \"src/main.py\", line 62, in train\n    env = NormalizedActions(gym.make(args.env_name))\n",
    "  File \"/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py\", line 167, in make\n    return registry.make(id)\n",
    "  File \"/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py\", line 119, in make\n    env = spec.make()\n",
    "  File \"/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py\", line 85, in make\n    cls = load(self._entry_point)\n",
    "  File \"/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py\", line 14, in load\n    result = entry_point.load(False)\n",
    "  File \"/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py\", line 2346, in load\n    return self.resolve()\n",
    "  File \"/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py\", line 2352, in resolve\n    module = __import__(self.module_name, fromlist=['__name__'], level=0)\n",
    "  File \"/usr/local/lib/python3.5/dist-packages/gym/envs/mujoco/__init__.py\", line 1, in <module>\n    from gym.envs.mujoco.mujoco_env import MujocoEnv\n",
    "  File \"/usr/local/lib/python3.5/dist-packages/gym/envs/mujoco/mujoco_env.py\", line 13, in <module>\n    raise error.DependencyNotInstalled(\"{}. (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)\".format(e))\n",
    "gym.error.DependencyNotInstalled: No module named 'mujoco_py'. (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)\n"
  ],
  "heartbeat": "2019-01-15T11:47:38.517578",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz",
    "gpus": {
      "driver_version": "387.26",
      "gpus": [
        {
          "model": "GeForce GTX 1080 Ti",
          "persistence_mode": false,
          "total_memory": 11172
        },
        {
          "model": "GeForce GTX 1080 Ti",
          "persistence_mode": false,
          "total_memory": 11172
        },
        {
          "model": "GeForce GTX 1080 Ti",
          "persistence_mode": false,
          "total_memory": 11172
        },
        {
          "model": "GeForce GTX 1080 Ti",
          "persistence_mode": false,
          "total_memory": 11172
        },
        {
          "model": "GeForce GTX 1080 Ti",
          "persistence_mode": false,
          "total_memory": 11172
        },
        {
          "model": "GeForce GTX 1080 Ti",
          "persistence_mode": false,
          "total_memory": 11172
        },
        {
          "model": "GeForce GTX 1080 Ti",
          "persistence_mode": false,
          "total_memory": 11172
        },
        {
          "model": "GeForce GTX 1080 Ti",
          "persistence_mode": false,
          "total_memory": 11172
        }
      ]
    },
    "hostname": "sauron",
    "os": [
      "Linux",
      "Linux-4.4.0-104-generic-x86_64-with-Ubuntu-16.04-xenial"
    ],
    "python_version": "3.5.2"
  },
  "meta": {
    "command": "my_main",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2019-01-15T11:47:38.424360",
  "status": "FAILED",
  "stop_time": "2019-01-15T11:47:38.521910"
}